title: VC Signed as a JWT
required:
  - credential_definition
  - format
type: object
properties:
  order:
    type: array
    description: OPTIONAL. Array of the claim name values that lists them in the order they should be displayed by the Wallet.
    items:
      type: string
  credential_definition:
    description: REQUIRED. Object containing the detailed description of the Credential type.
    type: object
    properties:
      type:
        type: array
        items:
          type: string
        description: REQUIRED. Array designating the types a certain Credential type supports, according to [VC_DATA], Section 4.3.
      credentialSubject:
        type: object
        description: >
          OPTIONAL. Object containing a list of name/value pairs, where each name identifies a claim offered in the Credential. 
          The value can be another such object (nested data structures), or an array of such objects.
        additionalProperties: true
  format:
    type: string
    description: >
      REQUIRED. A JSON string identifying the format of this Credential, i.e., `jwt_vc_json` or `mso_mdoc` or `vc+sd-jwt`. 
      Depending on the format value, the object contains further elements defining the type and (optionally) particular claims the Credential MAY contain and information about how to display the Credential.
  scope:
    type: string
    description: >
      OPTIONAL. A JSON string identifying the scope value that this Credential Issuer supports for this particular Credential. 
      The value can be the same across multiple credential_configurations_supported objects. 
      The Authorization Server MUST be able to uniquely identify the Credential Issuer based on the scope value. 
      The Wallet can use this value in the Authorization Request. 
      Scope values in this Credential Issuer metadata MAY duplicate those in the `scopes_supported parameter` of the Authorization Server.
  cryptographic_binding_methods_supported:
    type: array
    items:
      type: string
    description: >
      OPTIONAL. Array of case sensitive strings that identify the representation of the cryptographic key material that the issued Credential is bound to. Support for keys in JWK format [RFC7517] is indicated by the value jwk. 
      Support for keys expressed as a COSE Key object [RFC8152] (for example, used in [ISO.18013-5]) is indicated by the value cose_key. When the Cryptographic Binding Method is a DID, valid values are a did: prefix followed by a method-name using a syntax as defined in Section 3.1 of [DID-Core], but without a :and method-specific-id. For example, support for the DID method with a method-name "example" would be represented by did:example.
  credential_signing_alg_values_supported:
    description: >
      OPTIONAL. Array of case sensitive strings that identify the algorithms that the Issuer uses to sign the issued Credential.
    type: array
    items:
      type: string
  proof_types_supported:
    description: >
      Object that describes specifics of the key proof(s) that the Credential Issuer supports. 
      This object contains a list of name/value pairs, where each name is a unique identifier of the supported proof type(s). 
      This identifier is also used by the Wallet in the Credential Request.
    type: object
    properties:
      proof_signing_alg_values_supported:
        description: >
          REQUIRED. Array of case sensitive strings that identify the algorithms that the Issuer supports for this proof type. 
          The Wallet uses one of them to sign the proof.
        type: array
        items:
          type: string
  display:
    type: object
    description: Array of objects, where each object contains the display properties of the supported Credential for a certain language.
    properties:
      name:
        description: REQUIRED. String value of a display name for the Credential.
        type: string
      locale:
        type: string
        description: >
          OPTIONAL. String value that identifies the language of this object represented as a language tag taken from values defined in BCP47 [RFC5646].
          Multiple display objects MAY be included for separate languages. 
          There MUST be only one object for each language identifier.
      logo:
        type: object
        description: >
          OPTIONAL. Object with information about the logo of the Credential.
        properties:
          uri:
            type: string
            description: >
              REQUIRED. String value that contains a URI where the Wallet can obtain the logo of the Credential from the Credential Issuer. The Wallet needs to determine the scheme, since the URI value could use the https: scheme, the data: scheme, etc
          alt_text:
            type: string
            description: >
              OPTIONAL. String value of the alternative text for the logo image.
      description:
        type: string
        description: >
          OPTIONAL. String value of a description of the Credential.
      background_color:
        type: string
        description: >
          OPTIONAL. String value of a background color of the Credential represented as numerical color values defined in CSS Color Module Level 37 [CSS-Color].
      background_image:
        type: object
        description: >
          OPTIONAL. Object with information about the background image of the Credential.
        properties:
          uri:
            description: >
              REQUIRED. String value that contains a URI where the Wallet can obtain the background image of the Credential from the Credential Issuer. The Wallet needs to determine the scheme, since the URI value could use the https: scheme, the data: scheme, etc.
            type: string
      text_color:
        type: string
        description: >
          OPTIONAL. String value of a text color of the Credential represented as numerical color values defined in CSS Color Module Level 37 [CSS-Color].
